### PR TITLE
[WiP] Preview implementation with magnolia

### PR DESCRIPTION
**Pull request by krzemin**

### CODE REVIEW

**Comment by krzemin** [comment]
TODO:
- [ ] test coverage for async validators (#12)
- [ ] re-write async validator derivation with magnolia
- [ ] merge PR

**Comment by krzemin** [comment]
Also, want to explore #17 first, as final outcome may affect internals significantly.

**Comment by nafg** [comment]
I guess #17 has been explored, so what is the plan with this?

**Comment by krzemin** [comment]
I've tried implementing generic derivation with magnolia once again.

It works perfectly for `Validator` - eliminates the need of using shapeless-based generic derivation, speeds up compilation and simplifies implementation to just a few-lines snippet.

But I couldn't figure out how to implement derivation for `trait AsyncValidatorM[M[_], T]`. I tried to define type class similar to [`Show` example](https://github.com/propensive/magnolia/blob/master/examples/shared/src/main/scala/show.scala#L31):
```scala
class AsyncValidatorMDerivation[M[_]] {
  type Typeclass[T] = AsyncValidatorM[M, T]
  // other magnolia related stuff...
}

object AsyncValidatorM {
  ...
  implicit def derived[M[_], T]: AsyncValidatorM[M, T] =
    new AsyncValidatorMDerivation[M].derived[T]
}
```

This gives an error from magnolia macro:

```
[error] octopus/src/main/scala/octopus/AsyncValidator.scala:43:45: magnolia: could not infer AsyncValidatorMDerivation.Typeclass for type T
[error]     new AsyncValidatorMDerivation[M].derived[T]

```

However, it works when derivation is invoked for specific `M`, like:

```scala
implicit def derivedFuture[T]: AsyncValidatorM[Future, T] =
    new AsyncValidatorMDerivation[Future].derived[T]
```

It seems that magnolia gives up when it notices abstract type constructor somewhere in `Typeclass` definition.

**Pull request closed without merging**
